// <auto-generated />
using System;
using BlazorCurseach.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCurseach.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106170039_ItemImageLinks")]
    partial class ItemImageLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_520_ci")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlazorCurseach.Models.Category", b =>
                {
                    b.Property<int>("idCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Идентификатор категории");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idCategory"));

                    b.Property<string>("nameCategory")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasComment("Название категории товаров");

                    b.HasKey("idCategory")
                        .HasName("PRIMARY");

                    b.ToTable("Category", null, t =>
                        {
                            t.HasComment("Категория товара");
                        });
                });

            modelBuilder.Entity("BlazorCurseach.Models.CharacteristicItem", b =>
                {
                    b.Property<int>("idCharacteristicItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Идентификатор характеристики товара");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idCharacteristicItem"));

                    b.Property<int>("idCategory")
                        .HasColumnType("int")
                        .HasComment("Айди категории (FK)");

                    b.Property<string>("nameCharacteristicItem")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasComment("Название характеристики");

                    b.HasKey("idCharacteristicItem")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "idCategory" }, "fk_CharacteristicItem_Category1_idx");

                    b.ToTable("CharacteristicItem", null, t =>
                        {
                            t.HasComment("Характеристика товара");
                        });
                });

            modelBuilder.Entity("BlazorCurseach.Models.Client", b =>
                {
                    b.Property<int>("idClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Идентификатор клиента");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idClient"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Электронная почта клиента");

                    b.Property<string>("fatherName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasComment("Отчество клиента");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasComment("Имя клиента");

                    b.Property<int>("idRole")
                        .HasMaxLength(45)
                        .HasColumnType("int")
                        .HasComment("Айди роли конкретного клиента");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasComment("Фамилия клиента");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasComment("Логин клиента");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasComment("Пароль клиента");

                    b.Property<string>("phone")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasComment("Телефон клиента");

                    b.HasKey("idClient")
                        .HasName("PRIMARY");

                    b.HasIndex("idRole");

                    b.HasIndex(new[] { "login" }, "login_UNIQUE")
                        .IsUnique();

                    b.ToTable("Client", null, t =>
                        {
                            t.HasComment("Клиент веб-приложения (Пользователь)");
                        });
                });

            modelBuilder.Entity("BlazorCurseach.Models.Item", b =>
                {
                    b.Property<int>("idItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Идентификатор товара");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idItem"));

                    b.Property<int>("countItem")
                        .HasColumnType("int")
                        .HasComment("Доступное количество товаров");

                    b.Property<string>("descItem")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasComment("Описание товара");

                    b.Property<int>("idCategory")
                        .HasColumnType("int")
                        .HasComment("Идентификатор категории товара (FK)");

                    b.Property<string>("imageLink")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("Ссылка на изображение товара в приложении");

                    b.Property<sbyte>("inCart")
                        .HasColumnType("tinyint")
                        .HasComment("Флаг, определяющий, в корзине ли товар (по умолчанию false)");

                    b.Property<string>("nameItem")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)")
                        .HasComment("Название товара");

                    b.Property<double>("price")
                        .HasColumnType("double")
                        .HasComment("Цена товара");

                    b.HasKey("idItem")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "idCategory" }, "fk_Item_Category1_idx");

                    b.ToTable("Item", null, t =>
                        {
                            t.HasComment("Товар");
                        });
                });

            modelBuilder.Entity("BlazorCurseach.Models.Order", b =>
                {
                    b.Property<int>("idOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Идентификатор заказа");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idOrder"));

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime")
                        .HasComment("Дата создания заказа");

                    b.Property<string>("descOrder")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasComment("Описание заказа");

                    b.Property<int>("idClient")
                        .HasColumnType("int")
                        .HasComment("Айди клиента (FK)");

                    b.Property<int>("idStatusOrder")
                        .HasColumnType("int")
                        .HasComment("Идентификатор статуса заказа (FK)");

                    b.HasKey("idOrder")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "idClient" }, "fk_Order_Client1_idx");

                    b.HasIndex(new[] { "idStatusOrder" }, "fk_Order_StatusOrder_idx");

                    b.ToTable("Order", null, t =>
                        {
                            t.HasComment("Заказ");
                        });
                });

            modelBuilder.Entity("BlazorCurseach.Models.OrderItemTemp", b =>
                {
                    b.Property<int>("idItem")
                        .HasColumnType("int")
                        .HasComment("Айди товара для связи M:M (FK)");

                    b.Property<int>("idOrder")
                        .HasColumnType("int")
                        .HasComment("Айди заказа для связи M:M (FK)");

                    b.HasIndex(new[] { "idItem" }, "fk_table1_Item1_idx");

                    b.HasIndex(new[] { "idOrder" }, "fk_table1_Order1_idx");

                    b.ToTable("OrderItemTemp", null, t =>
                        {
                            t.HasComment("Таблица для обеспечения связи N:M (Item <-> Order)");
                        });
                });

            modelBuilder.Entity("BlazorCurseach.Models.StatusOrder", b =>
                {
                    b.Property<int>("idStatusOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Идентификатор статуса заказа");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idStatusOrder"));

                    b.Property<string>("nameStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("Название статуса заказа");

                    b.HasKey("idStatusOrder")
                        .HasName("PRIMARY");

                    b.ToTable("StatusOrder", null, t =>
                        {
                            t.HasComment("Статус заказа");
                        });
                });

            modelBuilder.Entity("BlazorCurseach.Models.UserRole", b =>
                {
                    b.Property<int>("idRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Идентификатор роли пользователя");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idRole"));

                    b.Property<string>("nameRole")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasComment("Название роли");

                    b.HasKey("idRole");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("BlazorCurseach.Models.ValueCharacteristic", b =>
                {
                    b.Property<int>("idValueCharacteristic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Идентификатор значения характеристики");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idValueCharacteristic"));

                    b.Property<int>("idCharacteristicItem")
                        .HasColumnType("int")
                        .HasComment("Айди характеристики (FK)");

                    b.Property<string>("selfValue")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasComment("Само значение характеристики (Spell Power = 15%)");

                    b.HasKey("idValueCharacteristic")
                        .HasName("PRIMARY");

                    b.HasIndex("idCharacteristicItem");

                    b.ToTable("ValueCharacteristic", null, t =>
                        {
                            t.HasComment("Значение характеристики товара");
                        });
                });

            modelBuilder.Entity("BlazorCurseach.Models.CharacteristicItem", b =>
                {
                    b.HasOne("BlazorCurseach.Models.Category", "idCategoryNavigation")
                        .WithMany("CharacteristicItems")
                        .HasForeignKey("idCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_CharacteristicItem_Category1_idx");

                    b.Navigation("idCategoryNavigation");
                });

            modelBuilder.Entity("BlazorCurseach.Models.Client", b =>
                {
                    b.HasOne("BlazorCurseach.Models.UserRole", "idUserRoleNavigation")
                        .WithMany("Clients")
                        .HasForeignKey("idRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("idUserRoleNavigation");
                });

            modelBuilder.Entity("BlazorCurseach.Models.Item", b =>
                {
                    b.HasOne("BlazorCurseach.Models.Category", "idCategoryNavigation")
                        .WithMany("Items")
                        .HasForeignKey("idCategory")
                        .IsRequired()
                        .HasConstraintName("fk_Item_Category1");

                    b.Navigation("idCategoryNavigation");
                });

            modelBuilder.Entity("BlazorCurseach.Models.Order", b =>
                {
                    b.HasOne("BlazorCurseach.Models.Client", "idClientNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("idClient")
                        .IsRequired()
                        .HasConstraintName("fk_Order_Client1");

                    b.HasOne("BlazorCurseach.Models.StatusOrder", "idStatusOrderNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("idStatusOrder")
                        .IsRequired()
                        .HasConstraintName("fk_Order_StatusOrder");

                    b.Navigation("idClientNavigation");

                    b.Navigation("idStatusOrderNavigation");
                });

            modelBuilder.Entity("BlazorCurseach.Models.OrderItemTemp", b =>
                {
                    b.HasOne("BlazorCurseach.Models.Item", "idItemNavigation")
                        .WithMany()
                        .HasForeignKey("idItem")
                        .IsRequired()
                        .HasConstraintName("fk_table1_Item1");

                    b.HasOne("BlazorCurseach.Models.Order", "idOrderNavigation")
                        .WithMany()
                        .HasForeignKey("idOrder")
                        .IsRequired()
                        .HasConstraintName("fk_table1_Order1");

                    b.Navigation("idItemNavigation");

                    b.Navigation("idOrderNavigation");
                });

            modelBuilder.Entity("BlazorCurseach.Models.ValueCharacteristic", b =>
                {
                    b.HasOne("BlazorCurseach.Models.CharacteristicItem", "idCharacteristicItemNavigation")
                        .WithMany("ValuesCharacteristic")
                        .HasForeignKey("idCharacteristicItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("idCharacteristicItemNavigation");
                });

            modelBuilder.Entity("BlazorCurseach.Models.Category", b =>
                {
                    b.Navigation("CharacteristicItems");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("BlazorCurseach.Models.CharacteristicItem", b =>
                {
                    b.Navigation("ValuesCharacteristic");
                });

            modelBuilder.Entity("BlazorCurseach.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BlazorCurseach.Models.StatusOrder", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BlazorCurseach.Models.UserRole", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
